### PR TITLE
added custom label

### PR DESCRIPTION
**Pull request by jasonmullins**

### CODE REVIEW

**Comment by ro-ka** [comment]
Could you explain what this is about? What is the use case?

Also: Please run npm test, because ES Lint is complaining. Not sure why Travis CI feedback isn’t visibile on PRs and commits in this project. Any ideas?

**Comment by jasonmullins** [comment]
Ok, it's fixed. Sorry about that.
So, the use case is this:
I'm setting country="us".  So I don't want the results to show the country like this: "San Francisco, CA, United States".  Basically, I just want it to be "San Francisco, CA".  The prop "getPlaceLabel" lets you provide your own function for building the label or description of the place.

**Comment by ro-ka** [comment]
Rebased because of other changes in the master branch. New PR is #52. Renamed to `getSuggestLabel` to keep the naming consistent.

**Comment by ro-ka** [comment]
Released with `1.10.0`.

**Pull request closed without merging**
