### PR TITLE
Bug fix for IE 10, 'this' is not defined in the constructor function.…

### PR DESCRIPTION
**Pull request by samdturner**
…  We need to access the props directly from the argument.

### CODE REVIEW

**Comment by samdturner** [comment]
Reopening PR #127 with the proper commits

**Comment by samdturner** [comment]
Guys, where are we on this one?

**Comment by ro-ka** [comment]
Thanks for the PR! And sorry for the late response.

**Comment by ro-ka** [comment]
Released with `1.23.0`. Thanks!

**Comment by samdturner** [comment]
Wonderful, thanks guys!

**Pull request merged**
