### PR TITLE
Wrappers functionality

### PR DESCRIPTION
**Pull request by msalsas**
I needed to wrap `input` element and suggestions `ul` element in a wrapper, so I forked this repository and added these options:

`wrapInput` (*boolean*) (and `inputWrapperClassName` (*string*))
`wrapSuggestionList` (*boolean*) (and `suggestionListWrapperClassName` (*string*))

Also added it to `README.md` and example.

You may want to merge it.

### CODE REVIEW

**Comment by ro-ka** [comment]
Thanks for the PR! What’s the reason to need some wrapper around these elements? Just asking, as this adds 4 more options to the module, which is quite a lot and I think most people won’t need them.

**Comment by msalsas** [comment]
The reason is that I need some custom styles for input and suggestion list. Those custom styles can only be set by wrapping `input` and `ul` elements (in my case). The limitation of CSS styling using the input and the list, both directly in a wrapper is relevant.

**Comment by ro-ka** [comment]
I’m just not sure if adding this to the module will make it more complicated to use. There are already a lot of options to choose from (I know, nothing that addresses your problem). Hope you get my point.

**Comment by msalsas** [comment]
I get it, but still think that it would be easier to style with the wrappers (in my case necessary). Don't you think so? 
It would be a pity to have to use a custom fork...

**Comment by ro-ka** [comment]
Was discussing this with @yfr over lunch – an idea was that maybe we should add the wrapper always with predefined classes (like the rest of the component) so that it is available but doesn’t complicate the amount of options available. What do you think?

**Comment by msalsas** [comment]
Perfect. Let me commit the changes.

**Comment by msalsas** [comment]
`geosuggest__input-wrapper` and `geosuggest__suggest-wrapper` or `geosuggest-input-wrapper` and `geosuggest-suggest-wrapper`? What do you think?

**Comment by msalsas** [comment]
Meanwhile, I used the first ones.

**Comment by ro-ka** [comment]
Great, thanks!

**Comment by ro-ka** [comment]
Released in npm. Made it that the wrappers are always added, keeps the options cleaner.  ;)

**Comment by msalsas** [comment]
Oh, I misunderstood your idea. I thought that you meant to keep the wrappers options, but not the classNames ones. Anyway, that's ok. Thanks for the workaround.

**Comment by ro-ka** [comment]
No problem :)  Thanks for contributing!

**Comment by msalsas** [comment]
It has been a pleasure :+1:

**Pull request merged**
