### PR TITLE
Allow adding custom classes to the suggest list and suggest item

### LINKED ISSUE #197: Support adding class names to suggests and suggest items
Is possible to set className for suggests and suggest items just as we set for inputClassName props?

This is my code

```
import React from 'react'
import classes from './LocationInputComponent.scss'
import Geosuggest from 'react-geosuggest';

export const LocationInputComponent = () => (
  <div>
    <Geosuggest
      inputClassName={ classes.geosuggest } />
  </div>
)
```

In the LocationInputComponent.scss file, I have exactly the same classes as [https://github.com/ubilabs/react-geosuggest/blob/master/src/geosuggest.css] 

The result of `classes.geosuggest` is something like this:  `geosuggest__input LocationInputComponent__geosuggest___91ULR`

I would like to be able to do something like this:

```
import React from 'react'
import classes from './LocationInputComponent.scss'
import Geosuggest from 'react-geosuggest';

export const LocationInputComponent = () => (
  <div>
    <Geosuggest
      inputClassName={ classes.geosuggest }
      suggestsClassName={ classes.geosuggest__suggests }
      suggestItemClassName={ classes.geosuggest__suggest__item } />
  </div>
)
```

I believe, this is the same (or almost the same) issue as: [https://github.com/ubilabs/react-geosuggest/issues/62]

### PR DESCRIPTION
**Pull request by karanjthakkar**
### Description

Fixes #197. Reuses the work done by @edudavid in https://github.com/ubilabs/react-geosuggest/pull/198

### Checklist

- [x] All tests passing
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary
- [x] Commits and PR follow conventions

### CODE REVIEW

**Comment by karanjthakkar** [comment]
@ro-ka I've made the classname changes like you mentioned in #253. And also added some tests for them.

**Comment by ro-ka** [comment]
Perfect, thank you!

**Comment by karanjthakkar** [comment]
@ro-ka Can you tell me when will you be pushing a new release with these changes?

**Comment by ro-ka** [comment]
Good news — just released! Version `2.1.0`. Thanks again!

**Pull request merged**
