### PR TITLE
Refactoring of the entire component and additional features

### PR DESCRIPTION
**Pull request by izziaraffaele**
I just refactored the entire component. I'll appreciate if you'll accept this PR otherwise we can keep components separated and I'll create a new repo for my version ;)

This PR adds
- Server-side rendering is now possible since the googleApi is initialized on componentDidMount
- GoogleApi simple requests cache 
- Props validation 
- A better way of organize the code ( this is just my point of view )
- Fix BEM classes in GeosuggestItem
- Moved React as peerDependency

Actually I just gave a fast check if things are working. Would be nice if you could test it as well. 

P.S. I just read later your guidelines for commit message style. Sorry for that

### CODE REVIEW

**Comment by ro-ka** [comment]
Hi,

you mixed up a lot of issues in one PR. That’s a bit hard to review and keep track of unexpected changes. Also, on a first view, there are a few breaking changes. I will not merge this PR as a whole, but we can add these things one by one. See my notes to your additions beneath. Also note that we have ES Lint and tests fail when it is not satisfied. (Not sure why Travis Checks don’t appear here.)

*I don’t think we need or want a fork. Willing to get your changes into this component.*

----

##### Server-side rendering is now possible since the googleApi is initialized on componentDidMount
--> Talking about that in #23. Will be implemented.

##### GoogleApi simple requests cache
--> Good idea, I’d like to add that.

##### Props validation
--> Sounds good, too.

##### A better way of organize the code ( this is just my point of view )
--> What purpose does a restructure satisfy? For the user of the component it doesn’t matter and it’s possible that it’ll introduce bugs. If we had tests, that are lacking in this project, it would be easier to do so. Also, we @ubilabs have our code style. Please respect that when contributing. (See ES Lint errors when running `npm test`.)

##### Fix BEM classes in GeosuggestItem
--> What’s the problem of the current structure? Kept them as individual modules, that’s why the items are individual.

##### Moved React as peerDependency
--> Like that.

**Comment by izziaraffaele** [comment]
Hi @ro-ka! I also noticed there are some other bugs on my code besides breaking changes. 

I agree with you that this PR should not be merged but most of the changes that are should be implemented to make this component better. So I pushed this PR to see if you like my idea and if we can work together on this.

I'm gonna open an issue for each of those points so that we can track discussions in a better way

**Comment by ro-ka** [comment]
That’s great!  :)

**Comment by izziaraffaele** [comment]
Ok done! Let's discuss on those issues and take this PR as inspiration ;)

**Comment by ro-ka** [comment]
Closing this as there are separate issues.

**Pull request closed without merging**
