### PR TITLE
method to change the value of the user input

### PR DESCRIPTION
**Pull request by juliocanares**
Sometimes we want to update the user input from out of the component by
example if we have an application as Uber the direction change dragging
the map, therefore the input needs to change too.

### CODE REVIEW

**Comment by ro-ka** [comment]
Thanks for your PR!
But please keep the existing code style and just add the feature you’d like to add.

**Comment by juliocanares** [comment]
@ro-ka I changed the code style :dancer:

**Comment by ro-ka** [comment]
Released as `1.8.0`.  Thanks!  :smiley:

**Comment by ro-ka** [comment]
Oh, named the function `update` just to be more consistent with the already existing `clear` function.

**Comment by juliocanares** [comment]
nice ^^

**Pull request merged**
