### PR TITLE
Test infrastructure

### LINKED ISSUE #53: Add component tests
It would be great if this component had tests, and code coverage metrics. We can use `mocha`, `sinon`, `jsdom`, `proxyquire` and `testUtils`.

Thoughts?

### PR DESCRIPTION
**Pull request by narendrashetty**
I have setup the test infrastructure for the repo. Also added the basic test for  component `Geosuggest`.
Fixes #53

### CODE REVIEW

**Comment by narendrashetty** [comment]
So, at the moment I've been using jsdom ^3.1.2 because it works with node.js as well as with iojs. But now it looks like there is no such version of jsdom that works with node 0.12 and node 4.x at the same time :(

**Comment by ro-ka** [comment]
Thanks for your efforts! We should definitely get this to work in the current Node version. As Node 4 is the current stable and LTS, I’m not sure if it would be an option to drop Node 0.12 from the tests. I don’t mean to drop it from being supported but from being tested. What do you think?

**Comment by narendrashetty** [comment]
@ro-ka Even I think the same. It's better to have the test on the latest version than not having the test at all.

**Comment by ro-ka** [comment]
Can you adjust the PR? Make it run in Node 4 and 5 and update the travis config to test those recent versions.

**Comment by narendrashetty** [comment]
@ro-ka made changes to run in Node 4 and 5. It works now :)

**Comment by ro-ka** [comment]
Fantastic! Thanks a lot!  :)

**Comment by ro-ka** [comment]
Somehow the test fail after the merge in Node 4: https://travis-ci.org/ubilabs/react-geosuggest/jobs/115270546

Do you have any idea why?

**Comment by narendrashetty** [comment]
looking into it

**Comment by narendrashetty** [comment]
screen shot 2016-03-11 at 4 01 37 pm

@ro-ka This error had occurred before and it was because the repo had older version of babel. I solved it by upgrading `babel` to `babel-cli`, but now it says babel to be installed globally do you think this could be the problem?

**Comment by ro-ka** [comment]
No, `babel`doesn’t have to be installed globally. *npm* checks the `./node_modules/.bin/` folder and executes from there if found.

But it looks like it doesn’t know the presets in the `package.json`. Maybe move them to an own file?

**Comment by narendrashetty** [comment]
Can you create `.babelrc` and add the below config
```
{
  "presets": [
    "es2015",
    "react"
  ]
}
```
Also remove the below config from `package.json`
```
"babel": {
    "presets": [
      "es2015",
      "react"
    ]
  }
```

**Comment by ro-ka** [comment]
Tested, but the same error occurs. Only in Node 4.   :/   Why did it work before the merge?

**Comment by narendrashetty** [comment]
really weird. If it worked in PR, it should work here. We are missing something very basic. 
It's working totally fine here in local. Do we set some different ENV for PR and master?

**Comment by ro-ka** [comment]
Didn’t set anything. Maybe it’s the cache? Not sure.  :/

**Comment by narendrashetty** [comment]
It still seems to be using old `babel`. Can we manually clear the cache?

**Comment by narendrashetty** [comment]
@ro-ka I still see the build error :( any updates?

**Comment by ro-ka** [comment]
Still have to take a look. Will do it soon.  :)

**Comment by ro-ka** [comment]
Okay, found out that there is a simple menu for the caches on Travis. Cleared all and reran the tests on master and it passed this time. :)  Thanks again!

**Pull request merged**
