### PR TITLE
triggering onSuggestSelect on all condition

### PR DESCRIPTION
**Pull request by narendrashetty**
### Description

Fixes a bug mentioned in issue #193 where `onSuggestSelect` was not fired when geocoding was unsuccessfully.
Made changes to fire `onSuggestSelect` on all cases.

### Checklist

- [x] All tests passing
- [x] Created tests which fail without the change (if possible)
- [x] Commits and PR follow conventions

### CODE REVIEW

**Comment by narendrashetty** [comment]
@yfr Hi, tests are working fine locally, am I missing anything?

**Comment by yfr** [comment]
Can't tell exactly what's going in the test `should reset the active suggest when it disappears from the list` on line 203 `onActivateSuggest.args` or `onActivateSuggest.args[0]` might not be ok.

**Comment by narendrashetty** [comment]
@yfr This PR should solve issue #193 . Thoughts?

**Comment by yfr** [comment]
Looks fine to me. Thanks!

**Pull request merged**
