### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by praveen612**
### Description

add prettier and make it work with ESLint 

### Checklist

- [x] All tests passing
- [ ] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary
- [x] Commits and PR follow conventions

### CODE REVIEW

**Comment by yfr** [comment]
Great idea. Let's work on this. We use prettier in our internal projects as well. I will check if we can adopt some of the workflows and settings for prettier we have.

**Comment by praveen612** [comment]
thank you, I will complete this PR soon and let you know.

**Comment by praveen612** [comment]
not sure why one of the Travis builds is failing here 😕

**Comment by praveen612** [comment]
@yfr can you check why one of the builds fails when you find the time?

**Pull request closed without merging**
