### PR TITLE
keep suggests hidden if onAfterInputChange triggers after input blur

### LINKED ISSUE #179: Input Blur before outstanding request returns
Quickly type in an address into the Geosuggest input, and tab out of the input before it has come back with suggestions. When the suggestions return, the geosuggest__suggests--hidden class is no longer applied to the suggestions and subsequent action on the page will not hide them until you activate the blur event on the input again.

On blur, any outstanding requests should be canceled and suggestions should not be shown.

### PR DESCRIPTION
**Pull request by rodrigo-castillo**
Closes #179

### CODE REVIEW

**Comment by Caerostris** [comment]
Thanks for this PR, @rodrigo-castillo 👍 
Please ensure that `npm run test` passes.
It's just a space between the `if` and the brackets.

**Comment by Caerostris** [comment]
The tests are still failing. You might have to focus the suggest box in the test cases now. This is just a wild guess though.

**Comment by rodrigo-castillo** [comment]
To be honest I'm having npm issues so I can't quite get the test harness installed yet. I'll keep poking at it until I can get that resolved.

**Comment by ro-ka** [comment]
Any progress on this one?

**Pull request closed without merging**
