### PR TITLE
Documented selectSuggest() in readme

### PR DESCRIPTION
**Pull request by joanrodriguez**
### Description

Just a quick edit to README.md

### Checklist

- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by ro-ka** [comment]
Thanks!  :)

**Comment by ecairol** [comment]
@joanrodriguez @ro-ka I can see that invoking `this._geoSuggest.selectSuggest()` executes the same result as hitting enter.

However, for both cases (hitting enter or invoking selectSuggest()) I'm getting a "INVALID_REQUEST".

The error happens inside the `geocodeSuggest()` function, the callback function for `this.placesService.getDetails()` runs with a `status = INVALID_REQUEST`

Any ideas what could be wrong? 
Thank you very much for your time and efforts building this plugin.

**Comment by ro-ka** [comment]
Is this still an issue? If yes, can you provide a demo of the error happening?

Sorry for the late answer.  😬

**Comment by ecairol** [comment]
I think so yeah, let me create an example.

**Pull request merged**
