### PR TITLE
Adding the allowed attributes details in the docs

### PR DESCRIPTION
**Pull request by narendrashetty**
This fixes the issue #218 

### Description
Added the list of allowed attributes on input tag to the docs

### CODE REVIEW

**Comment by narendrashetty** [comment]
@yfr Please have a look

**Comment by yfr** [comment]
@narendrashetty Sorry for the delay. Thank you for the PR. But would it not be easier to just add a link to the source? Now we have to change two places if an attribute changes.

**Comment by narendrashetty** [comment]
@yfr made the changes as mentioned :)

**Comment by yfr** [comment]
Perfect. Thanks!

**Pull request merged**
