### PR TITLE
test(Geosuggest): add coverage script to package.json

### PR DESCRIPTION
**Pull request by Caerostris**
Add a script `npm run coverage` which will generate code coverage reports.
Coverage is implemented using [nyc](https://www.npmjs.com/package/nyc), which is a wrapper for [istanbul](https://www.npmjs.com/package/istanbul). Unlike `istanbul`, however, it also works out of the box with babel.

### CODE REVIEW

**Comment by ro-ka** [comment]
Cool! Is it also possible to check the coverage? Maybe it should run with `npm run test` to see how much is covered.

**Comment by Caerostris** [comment]
Sure. We could also configure it so that `npm test` fails if the coverage falls below a certain threshold.

**Comment by ro-ka** [comment]
We can do that once we reach a certain coverage. ;)

**Comment by Caerostris** [comment]
Agreed ;)

**Pull request merged**
