### PR TITLE
Add property to set browser's native autocomplete. Set to off by defa…

### PR DESCRIPTION
**Pull request by Smudded**
…ult.

### CODE REVIEW

**Comment by Smudded** [comment]
Autocomplete is currently ignored in Chrome unless it is set on the form element, so if you test it in Chrome it will not function as expected. They should be fixing that soon though: https://code.google.com/p/chromium/issues/detail?id=468153#c123

**Comment by ro-ka** [comment]
Thanks for the PR!
Just tested the example in Chrome 47, the current stable. Works as expected. Which Chrome version are you running?

**Comment by Smudded** [comment]
I'm not 100% certain what the conditions are for Chrome to do its native autocomplete on forms, but the specific situation I had was a form field within a label that had the text Address in it as well. Chrome was then popping up its native autocomplete when the field was focused. I'm on my phone at the moment, but if you'd like I could set up the specific test case for you later this evening.

**Comment by ro-ka** [comment]
A test case would be great!

(Sorry for the late response… holidays. :) )

**Comment by ro-ka** [comment]
Hi! Can you provide a test case? Would like to see what you mean. :)

**Comment by ro-ka** [comment]
Closing because of missing feedback.

**Pull request closed without merging**
