### PR TITLE
feat(Geosuggest): add onActivateSuggest event

### PR DESCRIPTION
**Pull request by JeffreyATW**
I need to hook into the event that takes place when a new suggestion is activated, so I created an `onActivateSuggest` event prop. Tell me what you think.

### CODE REVIEW

**Comment by ro-ka** [comment]
Thanks for the PR! May I ask for a use case? Could this be solved differently? I want to avoid to add to many properties… :)

**Comment by JeffreyATW** [comment]
Sure, here's my example:
https://github.com/labzero/lunch/blob/master/src/components/RestaurantAddForm/RestaurantAddForm.js

The idea is, as the user activates different options, I geocode each Place ID to display a temporary marker on a Google map that's also on the page. This makes it easy to see exactly where each suggestion is, instead of depending on the address.

**Comment by ro-ka** [comment]
Hmm, that sounds reasonable… :)

**Comment by ro-ka** [comment]
By the way – bonus points for correct commit message and tests! Nice!
Released with `1.23.0`. Thanks!

**Pull request merged**
