### PR TITLE
chore: support react 17

### PR DESCRIPTION
**Pull request by dmossie**
### Description

I updated the peer dependencies to allow for react 17 and react-dom 17.
All the tests still pass, and it is running fine for me in my react 17 environment.
I believe I have followed all the conventions.
I did not update any documentation or tests.

### Checklist
- [X] All tests passing
- [X] Created tests which fail without the change (if possible)
- [X] Extended the README / documentation, if necessary
- [X] Commits and PR follow conventions

### CODE REVIEW

**Comment by yfr** [comment]
Hey. Thanks for the change.

Can you try updating the dev dependencies for react[-dom] to?

**Comment by dmossie** [comment]
Hey @yfr, no worries! I just updated the dev dependencies too.

**Comment by yfr** [comment]
Sorry, forgot to mention. We need updated type files too. `@types/react@latest` and `@types/react-dom@latest`.

**Comment by dmossie** [comment]
Hey @yfr , no worries. I just pushed another commit. Does that look right?

**Comment by yfr** [comment]
Thanks a lot! Look fine to me.

**Review by yfr — APPROVED** [review]

**Comment by yfr** [comment]
PR is merged. But I have issues creating the release. Will do as soon as possible.

**Pull request merged**
